### ISSUE TITLE
ateliers mathemathiques, functions_1

### ISSUE THREAD

**Issue by sgaydonohl** [42-AI/workshops_mathematics#2]
quelques suggestions de modifs :

Les fonctions
Partie leçon ("abc")
- [ ] 1. c'est ton choix, mais je pense que c'est pas la peine de dire à "un ou plusieurs nombres", c'est moins correct mais ça sera plus clair pour des débutants de lire "procédé qui relie un nombre à un autre".
- [x] 3. Ya un espace en trop entre le "3." et le début du paragraphe
- [x] 4. J'ai repris ta phrase mais formulée de façon plus claire :
L'ensemble de définition d'une fonction est l'ensemble des nombres réels pour lesquels on peut calculer une image. On le note D. 
- [x] 5. Je comprend pas vraiment le but du point 5, definir la notion d'expression algébrique?

Partie hint (ampoule)
- [x] il manque le 2.
- [x] ya un gap de niveau, et on comprend pas pourquoi tu donnes les formule, faudrait mettre un peu de contexte, ou dire que c'est des exemples. Sinon, le contenu est clair, le schéma est explicite ++ (sauf le mu qui n'apparait pas dans la formule au dessus, meme si on comprend bien qu'il shifte la fonction)

Les fonctions de références
Impec !! très clair

Somme et produit généralisés, sommation d'Einstein (titre corrigé) 
- [x] keep your fiche DRY : avant de détailler chacune des notations, juste en dessous de ce titre, tu peux dire que cest des notations qui permettent d'abréger les expressions algébriques, comme ça t'as pas besoin de l'écrire au début de chacune.

- [x] dans la somme généralisée, pour le troisième exemple, je mettrais les 9 composants de la somme, ça fait pas bcp et comme c'est une notion qui peut etre problèmatique pour certains, je clarifierais.
- [x] Produit généralisé (sans e !!)
Convention de sommation d'Einstein : impec

polynome du 2nd degré
- [x] Je pense que les . entre a et x², b et x ne sont pas nécessaires et peuvent mettre entrainer une confusion avec le dot product qu'on verra plus tard.

- [x] dans la partie discriminant, pour delta = 0, un "n'" s'est glissé
- [x] dans la variation de f(x), peut etre faire 3 row, 1 pour le signe (identique), 1 pour f(x) pour a < 0 (garder celle presente) et 1 pour a > 0 avec les pentes inversées
- [x] les différents scénarios sont hyper clairs

**Comment by madvid** [comment]
> 4. J'ai repris ta phrase mais formulée de façon plus claire : 
L'ensemble de définition d'une fonction est l'ensemble des nombres réels pour lesquels on peut calculer une image. On le note D.

J'ai gardé il existe car il y a une différence entre "on peut calculer une image" et "il existe une image"

**Comment by madvid** [comment]
J'ai pris en compte toutes tes corrections, merci pour l'issue.
