### ISSUE TITLE
Erreurs orthographe practise_sheet_1_functions.md

### ISSUE THREAD

**Issue by CharlieHMs** [42-AI/workshops_mathematics#31]
Ex1 :  

- [x]  "De même pour la notion d'ENSEMBLE de définition et l'ensemble image d'une fonction."

- [x] "(on remarque que la fonction f prend des valeurs compriseS entre -3 et 3 sur l'axe des ordonnées)"

- [x] "SOIT les fonctions g et h dont les représentations graphiques sont représentées sur la figure ci-dessous."

Ex 2 :
- [x] "Dans CET exercice, vous allez CALCULER des images de différentes fonctions à partir des EXPRESSIONS algébriques et tracer leurs représentations graphiques."
- [x] "le terme souvent UTILISÉ en maths est injecter"
- [x] "À vous de jouer ! SOIT les fonctions g et h"
- [x] "Par lecture graphique, QUELLES sont les coordonnées"
- [x] "Déterminer par le calcul, les coordonnées du POINT d'intersection"
- [x] "Note: Vous vous frotterez plus longuement aux systèmes d'équations lorsque vous serez à la DERNIERE fiche d'analyse."

Ex 3 : 
- [x] "Cette manière de faire sera pertinente lorsque l'on regardera les fonctions à plusieurs variables mais vous pouvez l'utiliser tout de même si vous le SOUHAITEZ."
- [x] "Partie 2: ANTECEDENTS"
- [x] "Vous pouvez alors écrire l'EQUATION suivante: "
- [x] "Votre boulot est de représenter l'ensemble des fonctions PRESENTES dans ce sujet, laissez votre côté artiste s'exprimer"

**Comment by madvid** [comment]
les fautes ont été corrigées.
